import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Pokit Code - Light & Fast Editor',
  description: 'Generated by create next app',
  icons: ['favicon.png']
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='font-space'>{children}</body>
    </html>
  )
}
