import type { Metadata } from 'next'
import './globals.css'
import { Analytics } from '@vercel/analytics/react';

export const metadata: Metadata = {
  title: 'Pokit Code - Light & Fast Editor',
  description: 'Generated by create next app',
  icons: ['favicon.png'],
  manifest: "/manifest.json", 
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='font-space'>
        {children}
        <Analytics />
      </body>
    </html>
  )
}
